# Generated by Django 5.2.15 on 2026-06-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('title', models.CharField(max_length=160, verbose_name='başlık')),
                ('title_tr', models.CharField(max_length=160, null=True, verbose_name='başlık')),
                ('title_en', models.CharField(max_length=160, null=True, verbose_name='başlık')),
                ('description', models.TextField(blank=True, verbose_name='açıklama')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='açıklama')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='açıklama')),
                ('date', models.DateField(blank=True, null=True, verbose_name='tarih')),
                ('image', models.ImageField(blank=True, upload_to='achievements/', verbose_name='görsel / ikon')),
            ],
            options={
                'verbose_name': 'Başarı',
                'verbose_name_plural': 'Başarılar',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('name', models.CharField(max_length=160, verbose_name='yarışma adı')),
                ('name_tr', models.CharField(max_length=160, null=True, verbose_name='yarışma adı')),
                ('name_en', models.CharField(max_length=160, null=True, verbose_name='yarışma adı')),
                ('season', models.CharField(blank=True, max_length=40, verbose_name='sezon')),
                ('date', models.DateField(blank=True, null=True, verbose_name='tarih')),
                ('location', models.CharField(blank=True, max_length=160, verbose_name='yer')),
                ('location_tr', models.CharField(blank=True, max_length=160, null=True, verbose_name='yer')),
                ('location_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='yer')),
                ('description', models.TextField(blank=True, verbose_name='açıklama')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='açıklama')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='açıklama')),
                ('result', models.CharField(blank=True, help_text="Örn. Bölge 3.'lüğü, Finalist", max_length=160, verbose_name='sonuç / derece')),
                ('result_tr', models.CharField(blank=True, help_text="Örn. Bölge 3.'lüğü, Finalist", max_length=160, null=True, verbose_name='sonuç / derece')),
                ('result_en', models.CharField(blank=True, help_text="Örn. Bölge 3.'lüğü, Finalist", max_length=160, null=True, verbose_name='sonuç / derece')),
                ('image', models.ImageField(blank=True, upload_to='competitions/', verbose_name='görsel')),
            ],
            options={
                'verbose_name': 'Yarışma',
                'verbose_name_plural': 'Yarışmalar',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
