# Generated by Django 5.2.15 on 2026-06-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=120, verbose_name='ad soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='e-posta')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefon')),
                ('subject', models.CharField(blank=True, max_length=160, verbose_name='konu')),
                ('message', models.TextField(verbose_name='mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='okundu')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
    ]
