# Generated by Django 5.2.15 on 2026-06-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Şablonda kullanılan benzersiz anahtar (örn. home_hero).', max_length=80, unique=True, verbose_name='anahtar')),
                ('label', models.CharField(help_text='Bu bloğun ne olduğunu açıklayan ad (admin için).', max_length=120, verbose_name='etiket')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='başlık')),
                ('title_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='başlık')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='başlık')),
                ('body', models.TextField(blank=True, verbose_name='metin')),
                ('body_tr', models.TextField(blank=True, null=True, verbose_name='metin')),
                ('body_en', models.TextField(blank=True, null=True, verbose_name='metin')),
                ('image', models.ImageField(blank=True, upload_to='pages/', verbose_name='görsel')),
            ],
            options={
                'verbose_name': 'Sayfa Metni',
                'verbose_name_plural': 'Sayfa Metinleri',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Çakatech', max_length=100, verbose_name='site adı')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='slogan')),
                ('tagline_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='slogan')),
                ('tagline_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='slogan')),
                ('about_short', models.TextField(blank=True, verbose_name='kısa tanıtım')),
                ('about_short_tr', models.TextField(blank=True, null=True, verbose_name='kısa tanıtım')),
                ('about_short_en', models.TextField(blank=True, null=True, verbose_name='kısa tanıtım')),
                ('logo', models.ImageField(blank=True, upload_to='site/', verbose_name='logo')),
                ('favicon', models.ImageField(blank=True, upload_to='site/', verbose_name='favicon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-posta')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefon')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adres')),
                ('address_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='adres')),
                ('address_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='adres')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter_url', models.URLField(blank=True, verbose_name='X / Twitter')),
                ('footer_text', models.CharField(blank=True, max_length=255, verbose_name='alt bilgi metni')),
                ('footer_text_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt bilgi metni')),
                ('footer_text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt bilgi metni')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
