# Generated by Django 5.2.15 on 2026-06-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('name', models.CharField(max_length=120, verbose_name='ad soyad')),
                ('role', models.CharField(blank=True, max_length=120, verbose_name='görev / unvan')),
                ('role_tr', models.CharField(blank=True, max_length=120, null=True, verbose_name='görev / unvan')),
                ('role_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='görev / unvan')),
                ('subteam', models.CharField(choices=[('captain', 'Kaptan'), ('mentor', 'Mentor'), ('mechanical', 'Mekanik'), ('software', 'Yazılım'), ('design', 'Tasarım / CAD'), ('media', 'Medya'), ('business', 'İş Geliştirme')], db_index=True, default='mechanical', max_length=20, verbose_name='alt takım')),
                ('bio', models.TextField(blank=True, verbose_name='kısa biyografi')),
                ('bio_tr', models.TextField(blank=True, null=True, verbose_name='kısa biyografi')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='kısa biyografi')),
                ('photo', models.ImageField(blank=True, upload_to='team/', verbose_name='fotoğraf')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
            ],
            options={
                'verbose_name': 'Üye',
                'verbose_name_plural': 'Üyeler',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
