# Generated by Django 5.2.15 on 2026-06-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('name', models.CharField(max_length=160, verbose_name='sponsor adı')),
                ('logo', models.ImageField(blank=True, upload_to='sponsors/', verbose_name='logo')),
                ('url', models.URLField(blank=True, verbose_name='web sitesi')),
                ('tier', models.CharField(choices=[('platinum', 'Platin'), ('gold', 'Altın'), ('silver', 'Gümüş'), ('bronze', 'Bronz'), ('partner', 'Partner')], db_index=True, default='partner', max_length=20, verbose_name='kategori')),
                ('description', models.TextField(blank=True, verbose_name='açıklama')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='açıklama')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='açıklama')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsorlar',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SponsorshipInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('name', models.CharField(max_length=120, verbose_name='ad soyad')),
                ('organization', models.CharField(blank=True, max_length=160, verbose_name='kurum / firma')),
                ('email', models.EmailField(max_length=254, verbose_name='e-posta')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefon')),
                ('message', models.TextField(verbose_name='mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='okundu')),
            ],
            options={
                'verbose_name': 'Sponsorluk Başvurusu',
                'verbose_name_plural': 'Sponsorluk Başvuruları',
                'ordering': ['-created_at'],
            },
        ),
    ]
